controller_list:
  - name: arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [sia10f_joint_s, sia10f_joint_l, sia10f_joint_e, sia10f_joint_u, sia10f_joint_r, sia10f_joint_b, sia10f_joint_t]
