controller_list:
  - name: arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [sia10f_joint_1_s, sia10f_joint_2_l, sia10f_joint_3_e, sia10f_joint_4_u, sia10f_joint_5_r, sia10f_joint_6_b, sia10f_joint_7_t]
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - finger_left_joint
      - finger_right_joint
