controller_list:
  - name: fake_arm_controller
    joints:
      - sia10f_joint_1_s
      - sia10f_joint_2_l
      - sia10f_joint_3_e
      - sia10f_joint_4_u
      - sia10f_joint_5_r
      - sia10f_joint_6_b
      - sia10f_joint_7_t
  - name: fake_gripper_controller
    joints:
      - finger_left_joint
      - finger_right_joint
