#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]

group1:
  group_name: yaskawa
  component_name: arm_left
  buttons: [[stop,trigger,stop],
    [init,trigger,init],
    [recover,trigger,recover],
    [home,move,home],
    [front,move,front]]
group2:
  group_name: gripper_pg70
  component_name: sia10f/gripper
  buttons: [[stop,trigger,stop],
    [init,trigger,init],
    [recover,trigger,recover],
    [open,move,open],
    [close,move,close]]
group3:
  group_name: gripper_lacquey
  component_name: ur5/gripper
  buttons: [[open,move,open],
    [close,move,close]]
